KS-20-5 print reversed phrase
DTigrusha/KotlinBasicByIVetrov pull request #101
Opened 2023-06-05 09:02 UTC by DTigrusha

2023-06-06 09:27 UTC, ievetrov requested changes

2023-06-07 08:03 UTC, ievetrov requested changes

2023-06-09 07:10 UTC, DTigrusha commented
Наотправляла лишних коммитов :(
Но вроде финальный вариант виден.

2023-06-10 13:18 UTC, ievetrov approved these changes
круто! все отлично

2023-06-10 16:19 UTC, merged